version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: acl_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test@123
    ports:
      - "5432:5432"
